require('./index.html')
require('./mars.jpg')
require('./rover.svg')
const Zone = require('./Zone')
const Rover = require('./Rover')

const canvas = document.getElementById("grid")

const zone = Zone(canvas, 10, 10, 30)
const rover = Rover(zone, 0, 0, "E")
rover.move()
rover.rotateLeft()
rover.move()
rover.rotateRight()
rover.move()
rover.move()
zone.drawGrid()
rover.drawRover()
